"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "ko" | "en" | "ja" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ko: {
    dashboard: "대시보드",
    fileShare: "파일 공유",
    advancedFileShare: "고급 파일공유", // 파일공유를 고급 파일공유로 변경
    webServer: "웹서버", // 웹서버 메뉴 추가
    webServerSettings: "웹서버 설정",
    webServerDescription: "웹서버 설정 및 기능을 구성합니다",
    customHostLabel: "사용자 정의 호스트",
    webFeatures: "웹 기능",
    browseAndShareFiles: "파일 탐색 및 공유",
    webControlPanel: "웹 제어판",
    activeServices: "활성 서비스",
    webFileShare: "웹 파일 공유",
    webDashboard: "웹 대시보드",
    serverPort: "서버 포트",
    documentRoot: "문서 루트",
    enableWebFileShare: "웹 파일 공유 활성화",
    enableWebDashboard: "웹 대시보드 활성화",
    startWebServer: "웹서버 시작",
    stopWebServer: "웹서버 중지",
    webServerStatus: "웹서버 상태",
    selectDocumentRoot: "문서 루트 선택",
    enabled: "활성화됨",
    disabled: "비활성화됨",
    status: "상태",
    hostSettings: "호스트 설정",
    localOnly: "내 컴퓨터만",
    allDevices: "모두에게",
    customHost: "직접 입력",
    webServerLog: "웹서버 로그",
    requestMethod: "요청 방법",
    requestPath: "요청 경로",
    statusCode: "상태 코드",
    responseTime: "응답 시간",
    userAgent: "사용자 에이전트",
    noWebServerLogs: "웹서버 로그가 없습니다",
    quickActions: "빠른 실행",
    personalData: "개인 데이터",
    settings: "설정",
    runningApps: "실행 중인 앱",
    systemStatus: "시스템 상태",
    recentFiles: "최근 파일",
    sftpConnection: "SFTP 연결",
    smbConnection: "SMB 연결",
    serverAddress: "서버 주소",
    username: "사용자명",
    password: "비밀번호",
    connect: "연결",
    disconnect: "연결 해제",
    connected: "연결됨",
    disconnected: "연결 해제됨",
    addShortcut: "단축키 추가",
    shortcutName: "단축키 이름",
    command: "명령어",
    save: "저장",
    delete: "삭제",
    edit: "편집",
    notes: "메모",
    documents: "문서",
    images: "이미지",
    videos: "비디오",
    language: "언어",
    theme: "테마",
    system: "시스템",
    light: "라이트",
    dark: "다크",
    cpu: "CPU",
    memory: "메모리",
    disk: "디스크",
    network: "네트워크",
    addNewItem: "새 항목 추가",
    title: "제목",
    type: "유형",
    content: "내용",
    add: "추가",
    noNotesStored: "저장된 메모가 없습니다.",
    noDocumentsStored: "저장된 문서가 없습니다.",
    noImagesStored: "저장된 이미지가 없습니다.",
    noVideosStored: "저장된 비디오가 없습니다.",
    serviceSettings: "서비스 설정",
    running: "실행 중",
    stopped: "중지됨",
    port: "포트",
    sharedFolder: "공유 폴더",
    accessPermissions: "접근 권한",
    readOnly: "읽기 전용",
    readWrite: "읽기/쓰기",
    startService: "서비스 시작",
    stopService: "서비스 중지",
    servicePath: "서비스 경로",
    accessLog: "접근 로그",
    timestamp: "시간",
    user: "사용자",
    ipAddress: "IP 주소",
    action: "작업",
    file: "파일",
    noAccessLogs: "접근 로그가 없습니다.",
    download: "다운로드",
    upload: "업로드",
    view: "조회",
    previous: "이전",
    next: "다음",
    page: "페이지",
    of: "의",
    showing: "표시 중",
    entries: "항목",
    services: "서비스",
    totalServices: "총 서비스",
    activeConnections: "활성 연결",
    dataTransfer: "데이터 전송",
    serviceStatus: "서비스 상태",
    connections: "연결",
    uptime: "가동 시간",
    sftpService: "SFTP 서비스",
    smbService: "SMB 서비스",
    hours: "시간",
    minutes: "분",
    seconds: "초",
    shortcutType: "단축키 타입",
    phone: "전화",
    email: "이메일",
    website: "웹사이트",
    application: "애플리케이션",
    custom: "직접 입력",
    phoneNumber: "전화번호",
    emailAddress: "이메일 주소",
    websiteUrl: "웹사이트 URL",
    applicationPath: "애플리케이션 경로",
    customCommand: "사용자 정의 명령",
    execute: "실행",
    noShortcutsYet: "아직 등록된 단축키가 없습니다.",
    addNewShortcut: "새로운 단축키를 추가해보세요.",
    expandSidebar: "사이드바 펼치기",
    collapseSidebar: "사이드바 접기",
    addQuickAction: "빠른 실행 추가",
    icon: "아이콘",
    selectIcon: "아이콘 선택",
    noIcon: "아이콘 없음",
    customImage: "사용자 정의 이미지",
    uploadCustomIcon: "사용자 정의 아이콘 업로드",
    imageUploaded: "이미지 업로드됨",
    ldapServer: "LDAP 서버",
    ldapConfiguration: "LDAP 구성",
    ldapUsers: "LDAP 사용자",
    ldapGroups: "LDAP 그룹",
    baseDN: "Base DN",
    bindDN: "Bind DN",
    bindPassword: "Bind 비밀번호",
    searchFilter: "검색 필터",
    userAttributes: "사용자 속성",
    groupAttributes: "그룹 속성",
    connectionTimeout: "연결 시간 초과",
    enableSSL: "SSL 활성화",
    enableTLS: "TLS 활성화",
    testConnection: "연결 테스트",
    connectionSuccessful: "연결 성공",
    connectionFailed: "연결 실패",
    syncUsers: "사용자 동기화",
    syncGroups: "그룹 동기화",
    lastSync: "마지막 동기화",
    ldapHosting: "LDAP 호스팅",
    ldapServiceStatus: "LDAP 서비스 상태",
    hostingPort: "호스팅 포트",
    domainName: "도메인 이름",
    adminUsername: "관리자 사용자명",
    adminPassword: "관리자 비밀번호",
    startLdapService: "LDAP 서비스 시작",
    stopLdapService: "LDAP 서비스 중지",
    createUser: "사용자 생성",
    createGroup: "그룹 생성",
    systemResources: "시스템 자원",
    usage: "사용량",
    available: "사용 가능",
    total: "전체",
    free: "여유",
    used: "사용됨",
    systemResourceDetails: "시스템 자원 상세",
    coreUsage: "코어 사용량",
    processes: "프로세스",
    temperature: "온도",
    frequency: "주파수",
    cached: "캐시됨",
    buffers: "버퍼",
    swap: "스왑",
    readSpeed: "읽기 속도",
    writeSpeed: "쓰기 속도",
    packetsReceived: "수신 패킷",
    packetsSent: "송신 패킷",
    core: "코어",
    cores: "코어",
    memoryUsage: "메모리 사용량",
    diskUsage: "디스크 사용량",
    networkInterfaces: "네트워크 인터페이스",
    macAddress: "MAC 주소",
    subnetMask: "서브넷 마스크",
    lanPorts: "랜 포트",
    activeSessions: "활성 세션",
    noActiveSessions: "활성 세션이 없습니다",
    sessionDuration: "세션 지속 시간",
    disconnectSession: "세션 끊기",
    korean: "한국어",
    english: "English",
    japanese: "日本語",
    chinese: "中文",
    ldapHostingDescription: "LDAP 서버 호스팅 설정 및 서비스 관리",
    ldapUsersDescription: "LDAP 서버의 사용자 계정 관리",
    ldapGroupsDescription: "LDAP 서버의 그룹 관리",
    createdDate: "생성일",
    members: "멤버",
    none: "없음",
    member: "member",
    members_plural: "members",
    sftpFolderSelection: "SFTP 폴더 선택",
    smbFolderSelection: "SMB 폴더 선택",
    selectFolder: "폴더 선택",
    themeProviderError: "useTheme은 ThemeProvider 내에서 사용되어야 합니다",
  },
  en: {
    dashboard: "Dashboard",
    fileShare: "File Share",
    advancedFileShare: "Advanced File Share", // 파일공유를 고급 파일공유로 변경
    webServer: "Web Server", // 웹서버 메뉴 추가
    webServerSettings: "Web Server Settings",
    webServerDescription: "Configure your web server settings and features",
    customHostLabel: "Custom Host",
    webFeatures: "Web Features",
    browseAndShareFiles: "Browse and share files",
    webControlPanel: "Web control panel",
    activeServices: "Active Services",
    webFileShare: "Web File Share",
    webDashboard: "Web Dashboard",
    serverPort: "Server Port",
    documentRoot: "Document Root",
    enableWebFileShare: "Enable Web File Share",
    enableWebDashboard: "Enable Web Dashboard",
    startWebServer: "Start Web Server",
    stopWebServer: "Stop Web Server",
    webServerStatus: "Web Server Status",
    selectDocumentRoot: "Select Document Root",
    enabled: "Enabled",
    disabled: "Disabled",
    status: "Status",
    hostSettings: "Host Settings",
    localOnly: "Local Only",
    allDevices: "All Devices",
    customHost: "Custom Host",
    webServerLog: "Web Server Log",
    requestMethod: "Request Method",
    requestPath: "Request Path",
    statusCode: "Status Code",
    responseTime: "Response Time",
    userAgent: "User Agent",
    noWebServerLogs: "No web server logs available",
    quickActions: "Quick Actions",
    personalData: "Personal Data",
    settings: "Settings",
    runningApps: "Running Apps",
    systemStatus: "System Status",
    recentFiles: "Recent Files",
    sftpConnection: "SFTP Connection",
    smbConnection: "SMB Connection",
    serverAddress: "Server Address",
    username: "Username",
    password: "Password",
    connect: "Connect",
    disconnect: "Disconnect",
    connected: "Connected",
    disconnected: "Disconnected",
    addShortcut: "Add Shortcut",
    shortcutName: "Shortcut Name",
    command: "Command",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    notes: "Notes",
    documents: "Documents",
    images: "Images",
    videos: "Videos",
    language: "Language",
    theme: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
    cpu: "CPU",
    memory: "Memory",
    disk: "Disk",
    network: "Network",
    addNewItem: "Add New Item",
    title: "Title",
    type: "Type",
    content: "Content",
    add: "Add",
    noNotesStored: "No notes stored.",
    noDocumentsStored: "No documents stored.",
    noImagesStored: "No images stored.",
    noVideosStored: "No videos stored.",
    serviceSettings: "Service Settings",
    running: "Running",
    stopped: "Stopped",
    port: "Port",
    sharedFolder: "Shared Folder",
    accessPermissions: "Access Permissions",
    readOnly: "Read Only",
    readWrite: "Read/Write",
    startService: "Start Service",
    stopService: "Stop Service",
    servicePath: "Service Path",
    accessLog: "Access Log",
    timestamp: "Timestamp",
    user: "User",
    ipAddress: "IP Address",
    action: "Action",
    file: "File",
    noAccessLogs: "No access logs available.",
    download: "Download",
    upload: "Upload",
    view: "View",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    showing: "Showing",
    entries: "entries",
    services: "Services",
    totalServices: "Total Services",
    activeConnections: "Active Connections",
    dataTransfer: "Data Transfer",
    serviceStatus: "Service Status",
    connections: "Connections",
    uptime: "Uptime",
    sftpService: "SFTP Service",
    smbService: "SMB Service",
    hours: "h",
    minutes: "m",
    seconds: "s",
    shortcutType: "Shortcut Type",
    phone: "Phone",
    email: "Email",
    website: "Website",
    application: "Application",
    custom: "Custom",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    websiteUrl: "Website URL",
    applicationPath: "Application Path",
    customCommand: "Custom Command",
    execute: "Execute",
    noShortcutsYet: "No shortcuts registered yet.",
    addNewShortcut: "Add a new shortcut.",
    expandSidebar: "Expand Sidebar",
    collapseSidebar: "Collapse Sidebar",
    addQuickAction: "Add Quick Action",
    icon: "Icon",
    selectIcon: "Select Icon",
    noIcon: "No Icon",
    customImage: "Custom Image",
    uploadCustomIcon: "Upload Custom Icon",
    imageUploaded: "Image Uploaded",
    ldapServer: "LDAP Server",
    ldapConfiguration: "LDAP Configuration",
    ldapUsers: "LDAP Users",
    ldapGroups: "LDAP Groups",
    baseDN: "Base DN",
    bindDN: "Bind DN",
    bindPassword: "Bind Password",
    searchFilter: "Search Filter",
    userAttributes: "User Attributes",
    groupAttributes: "Group Attributes",
    connectionTimeout: "Connection Timeout",
    enableSSL: "Enable SSL",
    enableTLS: "Enable TLS",
    testConnection: "Test Connection",
    connectionSuccessful: "Connection Successful",
    connectionFailed: "Connection Failed",
    syncUsers: "Sync Users",
    syncGroups: "Sync Groups",
    lastSync: "Last Sync",
    ldapHosting: "LDAP Hosting",
    ldapServiceStatus: "LDAP Service Status",
    hostingPort: "Hosting Port",
    domainName: "Domain Name",
    adminUsername: "Admin Username",
    adminPassword: "Admin Password",
    startLdapService: "Start LDAP Service",
    stopLdapService: "Stop LDAP Service",
    createUser: "Create User",
    createGroup: "Create Group",
    systemResources: "System Resources",
    usage: "Usage",
    available: "Available",
    total: "Total",
    free: "Free",
    used: "Used",
    systemResourceDetails: "System Resource Details",
    coreUsage: "Core Usage",
    processes: "Processes",
    temperature: "Temperature",
    frequency: "Frequency",
    cached: "Cached",
    buffers: "Buffers",
    swap: "Swap",
    readSpeed: "Read Speed",
    writeSpeed: "Write Speed",
    packetsReceived: "Packets Received",
    packetsSent: "Packets Sent",
    core: "Core",
    cores: "Cores",
    memoryUsage: "Memory Usage",
    diskUsage: "Disk Usage",
    networkInterfaces: "Network Interfaces",
    macAddress: "MAC Address",
    subnetMask: "Subnet Mask",
    lanPorts: "LAN Ports",
    activeSessions: "Active Sessions",
    noActiveSessions: "No active sessions",
    sessionDuration: "Session Duration",
    disconnectSession: "Disconnect Session",
    korean: "한국어",
    english: "English",
    japanese: "日本語",
    chinese: "中文",
    ldapHostingDescription: "LDAP server hosting settings and service management",
    ldapUsersDescription: "User account management for LDAP server",
    ldapGroupsDescription: "Group management for LDAP server",
    createdDate: "Created",
    members: "Members",
    none: "None",
    member: "member",
    members_plural: "members",
    sftpFolderSelection: "SFTP folder selection",
    smbFolderSelection: "SMB folder selection",
    selectFolder: "Select Folder",
    themeProviderError: "useTheme must be used within a ThemeProvider",
  },
  ja: {
    dashboard: "ダッシュボード",
    fileShare: "ファイル共有",
    advancedFileShare: "高度なファイル共有", // 파일공유를 고급 파일공유로 변경
    webServer: "ウェブサーバー", // 웹サーバー メニュー追加
    webServerSettings: "ウェブサーバー設定",
    webServerDescription: "ウェブサーバーの設定と機能を構成します",
    customHostLabel: "カスタムホスト",
    webFeatures: "ウェブ機能",
    browseAndShareFiles: "ファイルの閲覧と共有",
    webControlPanel: "ウェブコントロールパネル",
    activeServices: "アクティブサービス",
    webFileShare: "ウェブファイル共有",
    webDashboard: "ウェブダッシュボード",
    serverPort: "サーバーポート",
    documentRoot: "ドキュメントルート",
    enableWebFileShare: "ウェブファイル共有を有効化",
    enableWebDashboard: "ウェブダッシュボードを有効化",
    startWebServer: "ウェブサーバー開始",
    stopWebServer: "ウェブサーバー停止",
    webServerStatus: "ウェブサーバー状態",
    selectDocumentRoot: "ドキュメントルート選択",
    enabled: "有効",
    disabled: "無効",
    status: "状態",
    hostSettings: "ホスト設定",
    localOnly: "ローカルのみ",
    allDevices: "すべてのデバイス",
    customHost: "カスタムホスト",
    webServerLog: "ウェブサーバーログ",
    requestMethod: "リクエストメソッド",
    requestPath: "リクエストパス",
    statusCode: "ステータスコード",
    responseTime: "レスポンス時間",
    userAgent: "ユーザーエージェント",
    noWebServerLogs: "ウェブサーバーログがありません",
    quickActions: "クイックアクション",
    personalData: "個人データ",
    settings: "設定",
    runningApps: "実行中のアプリ",
    systemStatus: "システム状態",
    recentFiles: "最近のファイル",
    sftpConnection: "SFTP接続",
    smbConnection: "SMB接続",
    serverAddress: "サーバーアドレス",
    username: "ユーザー名",
    password: "パスワード",
    connect: "接続",
    disconnect: "切断",
    connected: "接続済み",
    disconnected: "切断済み",
    addShortcut: "ショートカット追加",
    shortcutName: "ショートカット名",
    command: "コマンド",
    save: "保存",
    delete: "削除",
    edit: "編集",
    notes: "メモ",
    documents: "ドキュメント",
    images: "画像",
    videos: "ビデオ",
    language: "言語",
    theme: "テーマ",
    system: "システム",
    light: "ライト",
    dark: "ダーク",
    cpu: "CPU",
    memory: "メモリ",
    disk: "ディスク",
    network: "ネットワーク",
    addNewItem: "新しいアイテムを追加",
    title: "タイトル",
    type: "タイプ",
    content: "内容",
    add: "追加",
    noNotesStored: "保存されたメモはありません。",
    noDocumentsStored: "保存されたドキュメントはありません。",
    noImagesStored: "保存された画像はありません。",
    noVideosStored: "保存されたビデオはありません。",
    serviceSettings: "サービス設定",
    running: "実行中",
    stopped: "停止中",
    port: "ポート",
    sharedFolder: "共有フォルダ",
    accessPermissions: "アクセス権限",
    readOnly: "読み取り専用",
    readWrite: "読み書き",
    startService: "サービス開始",
    stopService: "サービス停止",
    servicePath: "サービスパス",
    accessLog: "アクセスログ",
    timestamp: "タイムスタンプ",
    user: "ユーザー",
    ipAddress: "IPアドレス",
    action: "アクション",
    file: "ファイル",
    noAccessLogs: "アクセスログがありません。",
    download: "ダウンロード",
    upload: "アップロード",
    view: "表示",
    previous: "前へ",
    next: "次へ",
    page: "ページ",
    of: "の",
    showing: "表示中",
    entries: "件",
    services: "サービス",
    totalServices: "総サービス数",
    activeConnections: "アクティブ接続",
    dataTransfer: "データ転送",
    serviceStatus: "サービス状態",
    connections: "接続",
    uptime: "稼働時間",
    sftpService: "SFTPサービス",
    smbService: "SMBサービス",
    hours: "時間",
    minutes: "分",
    seconds: "秒",
    shortcutType: "ショートカットタイプ",
    phone: "電話",
    email: "メール",
    website: "ウェブサイト",
    application: "アプリケーション",
    custom: "カスタム",
    phoneNumber: "電話番号",
    emailAddress: "メールアドレス",
    websiteUrl: "ウェブサイトURL",
    applicationPath: "アプリケーションパス",
    customCommand: "カスタムコマンド",
    execute: "実行",
    noShortcutsYet: "まだショートカットが登録されていません。",
    addNewShortcut: "新しいショートカットを追加してください。",
    expandSidebar: "サイドバーを展開",
    collapseSidebar: "サイドバーを折りたたむ",
    addQuickAction: "クイックアクション追加",
    icon: "アイコン",
    selectIcon: "アイコン選択",
    noIcon: "アイコンなし",
    customImage: "カスタム画像",
    uploadCustomIcon: "カスタムアイコンアップロード",
    imageUploaded: "画像アップロード済み",
    ldapServer: "LDAPサーバー",
    ldapConfiguration: "LDAP設定",
    ldapUsers: "LDAPユーザー",
    ldapGroups: "LDAPグループ",
    baseDN: "ベースDN",
    bindDN: "バインドDN",
    bindPassword: "バインドパスワード",
    searchFilter: "検索フィルター",
    userAttributes: "ユーザー属性",
    groupAttributes: "グループ属性",
    connectionTimeout: "接続タイムアウト",
    enableSSL: "SSL有効化",
    enableTLS: "TLS有効化",
    testConnection: "接続テスト",
    connectionSuccessful: "接続成功",
    connectionFailed: "接続失敗",
    syncUsers: "ユーザー同期",
    syncGroups: "グループ同期",
    lastSync: "最終同期",
    ldapHosting: "LDAPホスティング",
    ldapServiceStatus: "LDAPサービス状態",
    hostingPort: "ホスティングポート",
    domainName: "ドメイン名",
    adminUsername: "管理者ユーザー名",
    adminPassword: "管理者パスワード",
    startLdapService: "LDAPサービス開始",
    stopLdapService: "LDAPサービス停止",
    createUser: "ユーザー作成",
    createGroup: "グループ作成",
    systemResources: "システムリソース",
    usage: "使用量",
    available: "利用可能",
    total: "合計",
    free: "空き",
    used: "使用中",
    systemResourceDetails: "システムリソース詳細",
    coreUsage: "コア使用量",
    processes: "プロセス",
    temperature: "温度",
    frequency: "周波数",
    cached: "キャッシュ済み",
    buffers: "バッファ",
    swap: "スワップ",
    readSpeed: "読み取り速度",
    writeSpeed: "書き込み速度",
    packetsReceived: "受信パケット",
    packetsSent: "送信パケット",
    core: "コア",
    cores: "コア",
    memoryUsage: "メモリ使用量",
    diskUsage: "ディスク使用量",
    networkInterfaces: "ネットワークインターフェース",
    macAddress: "MACアドレス",
    subnetMask: "サブネットマスク",
    lanPorts: "LANポート",
    activeSessions: "アクティブセッション",
    noActiveSessions: "アクティブセッションがありません",
    sessionDuration: "セッション継続時間",
    disconnectSession: "セッション切断",
    korean: "한국어",
    english: "English",
    japanese: "日本語",
    chinese: "中文",
    ldapHostingDescription: "LDAPサーバーホスティング設定とサービス管理",
    ldapUsersDescription: "LDAPサーバーのユーザーアカウント管理",
    ldapGroupsDescription: "LDAPサーバーのグループ管理",
    createdDate: "作成日",
    members: "メンバー",
    none: "なし",
    member: "メンバー",
    members_plural: "メンバー",
    sftpFolderSelection: "SFTPフォルダ選択",
    smbFolderSelection: "SMBフォルダ選択",
    selectFolder: "フォルダ選択",
    themeProviderError: "useThemeはThemeProvider内で使用する必要があります",
  },
  zh: {
    dashboard: "仪表板",
    fileShare: "文件共享",
    advancedFileShare: "高级文件共享", // 文件공유를 고급 파일공유로 변경
    webServer: "网络服务器", // 웹서버 메뉴 추가
    webServerSettings: "网络服务器设置",
    webServerDescription: "配置您的网络服务器设置和功能",
    customHostLabel: "自定义主机",
    webFeatures: "网络功能",
    browseAndShareFiles: "浏览和共享文件",
    webControlPanel: "网络控制面板",
    activeServices: "活动服务",
    webFileShare: "网络文件共享",
    webDashboard: "网络仪表板",
    serverPort: "服务器端口",
    documentRoot: "文档根目录",
    enableWebFileShare: "启用网络文件共享",
    enableWebDashboard: "启用网络仪表板",
    startWebServer: "启动网络服务器",
    stopWebServer: "停止网络服务器",
    webServerStatus: "网络服务器状态",
    selectDocumentRoot: "选择文档根目录",
    enabled: "已启用",
    disabled: "已禁用",
    status: "状态",
    hostSettings: "主机设置",
    localOnly: "仅本机",
    allDevices: "所有设备",
    customHost: "自定义主机",
    webServerLog: "网络服务器日志",
    requestMethod: "请求方法",
    requestPath: "请求路径",
    statusCode: "状态码",
    responseTime: "响应时间",
    userAgent: "用户代理",
    noWebServerLogs: "没有网络服务器日志",
    quickActions: "快速操作",
    personalData: "个人数据",
    settings: "设置",
    runningApps: "运行中的应用",
    systemStatus: "系统状态",
    recentFiles: "最近文件",
    sftpConnection: "SFTP连接",
    smbConnection: "SMB连接",
    serverAddress: "服务器地址",
    username: "用户名",
    password: "密码",
    connect: "连接",
    disconnect: "断开连接",
    connected: "已连接",
    disconnected: "已断开",
    addShortcut: "添加快捷方式",
    shortcutName: "快捷方式名称",
    command: "命令",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    notes: "笔记",
    documents: "文档",
    images: "图片",
    videos: "视频",
    language: "语言",
    theme: "主题",
    system: "系统",
    light: "浅色",
    dark: "深色",
    cpu: "CPU",
    memory: "内存",
    disk: "磁盘",
    network: "网络",
    addNewItem: "添加新项目",
    title: "标题",
    type: "类型",
    content: "内容",
    add: "添加",
    noNotesStored: "没有保存的笔记。",
    noDocumentsStored: "没有保存的文档。",
    noImagesStored: "没有保存的图片。",
    noVideosStored: "没有保存的视频。",
    serviceSettings: "服务设置",
    running: "运行中",
    stopped: "已停止",
    port: "端口",
    sharedFolder: "共享文件夹",
    accessPermissions: "访问权限",
    readOnly: "只读",
    readWrite: "读写",
    startService: "启动服务",
    stopService: "停止服务",
    servicePath: "服务路径",
    accessLog: "访问日志",
    timestamp: "时间戳",
    user: "用户",
    ipAddress: "IP地址",
    action: "操作",
    file: "文件",
    noAccessLogs: "没有访问日志。",
    download: "下载",
    upload: "上传",
    view: "查看",
    previous: "上一页",
    next: "下一页",
    page: "页",
    of: "共",
    showing: "显示",
    entries: "条",
    services: "服务",
    totalServices: "总服务数",
    activeConnections: "活跃连接",
    dataTransfer: "数据传输",
    serviceStatus: "服务状态",
    connections: "连接",
    uptime: "运行时间",
    sftpService: "SFTP服务",
    smbService: "SMB服务",
    hours: "小时",
    minutes: "分钟",
    seconds: "秒",
    shortcutType: "快捷方式类型",
    phone: "电话",
    email: "邮件",
    website: "网站",
    application: "应用程序",
    custom: "自定义",
    phoneNumber: "电话号码",
    emailAddress: "邮箱地址",
    websiteUrl: "网站URL",
    applicationPath: "应用程序路径",
    customCommand: "自定义命令",
    execute: "执行",
    noShortcutsYet: "还没有注册的快捷方式。",
    addNewShortcut: "添加新的快捷方式。",
    expandSidebar: "展开侧边栏",
    collapseSidebar: "折叠侧边栏",
    addQuickAction: "添加快速操作",
    icon: "图标",
    selectIcon: "选择图标",
    noIcon: "无图标",
    customImage: "自定义图片",
    uploadCustomIcon: "上传自定义图标",
    imageUploaded: "图片已上传",
    ldapServer: "LDAP服务器",
    ldapConfiguration: "LDAP配置",
    ldapUsers: "LDAP用户",
    ldapGroups: "LDAP组",
    baseDN: "基础DN",
    bindDN: "绑定DN",
    bindPassword: "绑定密码",
    searchFilter: "搜索过滤器",
    userAttributes: "用户属性",
    groupAttributes: "组属性",
    connectionTimeout: "连接超时",
    enableSSL: "启用SSL",
    enableTLS: "启用TLS",
    testConnection: "测试连接",
    connectionSuccessful: "连接成功",
    connectionFailed: "连接失败",
    syncUsers: "同步用户",
    syncGroups: "同步组",
    lastSync: "最后同步",
    ldapHosting: "LDAP托管",
    ldapServiceStatus: "LDAP服务状态",
    hostingPort: "托管端口",
    domainName: "域名",
    adminUsername: "管理员用户名",
    adminPassword: "管理员密码",
    startLdapService: "启动LDAP服务",
    stopLdapService: "停止LDAP服务",
    createUser: "创建用户",
    createGroup: "创建组",
    systemResources: "系统资源",
    usage: "使用量",
    available: "可用",
    total: "总计",
    free: "空闲",
    used: "已使用",
    systemResourceDetails: "系统资源详情",
    coreUsage: "核心使用量",
    processes: "进程",
    temperature: "温度",
    frequency: "频率",
    cached: "已缓存",
    buffers: "缓冲区",
    swap: "交换区",
    readSpeed: "读取速度",
    writeSpeed: "写入速度",
    packetsReceived: "接收数据包",
    packetsSent: "发送数据包",
    core: "核心",
    cores: "核心",
    memoryUsage: "内存使用量",
    diskUsage: "磁盘使用量",
    networkInterfaces: "网络接口",
    macAddress: "MAC地址",
    subnetMask: "子网掩码",
    lanPorts: "局域网端口",
    activeSessions: "活跃会话",
    noActiveSessions: "没有活跃会话",
    sessionDuration: "会话持续时间",
    disconnectSession: "断开会话",
    korean: "한국어",
    english: "English",
    japanese: "日本語",
    chinese: "中文",
    ldapHostingDescription: "LDAP服务器托管设置和服务管理",
    ldapUsersDescription: "LDAP服务器的用户账户管理",
    ldapGroupsDescription: "LDAP服务器的组管理",
    createdDate: "创建日期",
    members: "成员",
    none: "无",
    member: "成员",
    members_plural: "成员",
    sftpFolderSelection: "SFTP文件夹选择",
    smbFolderSelection: "SMB文件夹选择",
    selectFolder: "选择文件夹",
    themeProviderError: "useTheme必须在ThemeProvider内使用",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ko")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("caw-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("caw-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[Language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
