"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "ko" | "en" | "ja" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ko: {
    dashboard: "대시보드",
    fileShare: "파일 공유",
    quickActions: "빠른 실행",
    personalData: "개인 데이터",
    settings: "설정",
    runningApps: "실행 중인 앱",
    systemStatus: "시스템 상태",
    recentFiles: "최근 파일",
    sftpConnection: "SFTP 연결",
    smbConnection: "SMB 연결",
    serverAddress: "서버 주소",
    username: "사용자명",
    password: "비밀번호",
    connect: "연결",
    disconnect: "연결 해제",
    connected: "연결됨",
    disconnected: "연결 해제됨",
    addShortcut: "단축키 추가",
    shortcutName: "단축키 이름",
    command: "명령어",
    save: "저장",
    delete: "삭제",
    edit: "편집",
    notes: "메모",
    documents: "문서",
    images: "이미지",
    videos: "비디오",
    language: "언어",
    theme: "테마",
    system: "시스템",
    light: "라이트",
    dark: "다크",
    cpu: "CPU",
    memory: "메모리",
    disk: "디스크",
    network: "네트워크",
    addNewItem: "새 항목 추가",
    title: "제목",
    type: "유형",
    content: "내용",
    add: "추가",
    noNotesStored: "저장된 메모가 없습니다.",
    noDocumentsStored: "저장된 문서가 없습니다.",
    noImagesStored: "저장된 이미지가 없습니다.",
    noVideosStored: "저장된 비디오가 없습니다.",
    serviceSettings: "서비스 설정",
    running: "실행 중",
    stopped: "중지됨",
    port: "포트",
    sharedFolder: "공유 폴더",
    accessPermissions: "접근 권한",
    readOnly: "읽기 전용",
    readWrite: "읽기/쓰기",
    startService: "서비스 시작",
    stopService: "서비스 중지",
    servicePath: "서비스 경로",
    accessLog: "접근 로그",
    timestamp: "시간",
    user: "사용자",
    ipAddress: "IP 주소",
    action: "작업",
    file: "파일",
    noAccessLogs: "접근 로그가 없습니다.",
    download: "다운로드",
    upload: "업로드",
    view: "조회",
    previous: "이전",
    next: "다음",
    page: "페이지",
    of: "의",
    showing: "표시 중",
    entries: "항목",
    services: "서비스",
    totalServices: "총 서비스",
    activeServices: "활성 서비스",
    activeConnections: "활성 연결",
    dataTransfer: "데이터 전송",
    serviceStatus: "서비스 상태",
    connections: "연결",
    uptime: "가동 시간",
    sftpService: "SFTP 서비스",
    smbService: "SMB 서비스",
    hours: "시간",
    minutes: "분",
    seconds: "초",
    shortcutType: "단축키 타입",
    phone: "전화",
    email: "이메일",
    website: "웹사이트",
    application: "애플리케이션",
    custom: "직접 입력",
    phoneNumber: "전화번호",
    emailAddress: "이메일 주소",
    websiteUrl: "웹사이트 URL",
    applicationPath: "애플리케이션 경로",
    customCommand: "사용자 정의 명령",
    execute: "실행",
    noShortcutsYet: "아직 등록된 단축키가 없습니다.",
    addNewShortcut: "새로운 단축키를 추가해보세요.",
    expandSidebar: "사이드바 펼치기",
    collapseSidebar: "사이드바 접기",
    addQuickAction: "빠른 실행 추가",
    icon: "아이콘",
    selectIcon: "아이콘 선택",
    noIcon: "아이콘 없음",
    customImage: "사용자 정의 이미지",
    uploadCustomIcon: "사용자 정의 아이콘 업로드",
    imageUploaded: "이미지 업로드됨",
    ldapServer: "LDAP 서버",
    ldapConfiguration: "LDAP 구성",
    ldapUsers: "LDAP 사용자",
    ldapGroups: "LDAP 그룹",
    baseDN: "Base DN",
    bindDN: "Bind DN",
    bindPassword: "Bind 비밀번호",
    searchFilter: "검색 필터",
    userAttributes: "사용자 속성",
    groupAttributes: "그룹 속성",
    connectionTimeout: "연결 시간 초과",
    enableSSL: "SSL 활성화",
    enableTLS: "TLS 활성화",
    testConnection: "연결 테스트",
    connectionSuccessful: "연결 성공",
    connectionFailed: "연결 실패",
    syncUsers: "사용자 동기화",
    syncGroups: "그룹 동기화",
    lastSync: "마지막 동기화",
    ldapHosting: "LDAP 호스팅",
    ldapServiceStatus: "LDAP 서비스 상태",
    hostingPort: "호스팅 포트",
    domainName: "도메인 이름",
    adminUsername: "관리자 사용자명",
    adminPassword: "관리자 비밀번호",
    startLdapService: "LDAP 서비스 시작",
    stopLdapService: "LDAP 서비스 중지",
    createUser: "사용자 생성",
    createGroup: "그룹 생성",
  },
  en: {
    dashboard: "Dashboard",
    fileShare: "File Share",
    quickActions: "Quick Actions",
    personalData: "Personal Data",
    settings: "Settings",
    runningApps: "Running Apps",
    systemStatus: "System Status",
    recentFiles: "Recent Files",
    sftpConnection: "SFTP Connection",
    smbConnection: "SMB Connection",
    serverAddress: "Server Address",
    username: "Username",
    password: "Password",
    connect: "Connect",
    disconnect: "Disconnect",
    connected: "Connected",
    disconnected: "Disconnected",
    addShortcut: "Add Shortcut",
    shortcutName: "Shortcut Name",
    command: "Command",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    notes: "Notes",
    documents: "Documents",
    images: "Images",
    videos: "Videos",
    language: "Language",
    theme: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
    cpu: "CPU",
    memory: "Memory",
    disk: "Disk",
    network: "Network",
    addNewItem: "Add New Item",
    title: "Title",
    type: "Type",
    content: "Content",
    add: "Add",
    noNotesStored: "No notes stored.",
    noDocumentsStored: "No documents stored.",
    noImagesStored: "No images stored.",
    noVideosStored: "No videos stored.",
    serviceSettings: "Service Settings",
    running: "Running",
    stopped: "Stopped",
    port: "Port",
    sharedFolder: "Shared Folder",
    accessPermissions: "Access Permissions",
    readOnly: "Read Only",
    readWrite: "Read/Write",
    startService: "Start Service",
    stopService: "Stop Service",
    servicePath: "Service Path",
    accessLog: "Access Log",
    timestamp: "Timestamp",
    user: "User",
    ipAddress: "IP Address",
    action: "Action",
    file: "File",
    noAccessLogs: "No access logs available.",
    download: "Download",
    upload: "Upload",
    view: "View",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    showing: "Showing",
    entries: "entries",
    services: "Services",
    totalServices: "Total Services",
    activeServices: "Active Services",
    activeConnections: "Active Connections",
    dataTransfer: "Data Transfer",
    serviceStatus: "Service Status",
    connections: "Connections",
    uptime: "Uptime",
    sftpService: "SFTP Service",
    smbService: "SMB Service",
    hours: "h",
    minutes: "m",
    seconds: "s",
    shortcutType: "Shortcut Type",
    phone: "Phone",
    email: "Email",
    website: "Website",
    application: "Application",
    custom: "Custom",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    websiteUrl: "Website URL",
    applicationPath: "Application Path",
    customCommand: "Custom Command",
    execute: "Execute",
    noShortcutsYet: "No shortcuts registered yet.",
    addNewShortcut: "Add a new shortcut.",
    expandSidebar: "Expand Sidebar",
    collapseSidebar: "Collapse Sidebar",
    addQuickAction: "Add Quick Action",
    icon: "Icon",
    selectIcon: "Select Icon",
    noIcon: "No Icon",
    customImage: "Custom Image",
    uploadCustomIcon: "Upload Custom Icon",
    imageUploaded: "Image Uploaded",
    ldapServer: "LDAP Server",
    ldapConfiguration: "LDAP Configuration",
    ldapUsers: "LDAP Users",
    ldapGroups: "LDAP Groups",
    baseDN: "Base DN",
    bindDN: "Bind DN",
    bindPassword: "Bind Password",
    searchFilter: "Search Filter",
    userAttributes: "User Attributes",
    groupAttributes: "Group Attributes",
    connectionTimeout: "Connection Timeout",
    enableSSL: "Enable SSL",
    enableTLS: "Enable TLS",
    testConnection: "Test Connection",
    connectionSuccessful: "Connection Successful",
    connectionFailed: "Connection Failed",
    syncUsers: "Sync Users",
    syncGroups: "Sync Groups",
    lastSync: "Last Sync",
    ldapHosting: "LDAP Hosting",
    ldapServiceStatus: "LDAP Service Status",
    hostingPort: "Hosting Port",
    domainName: "Domain Name",
    adminUsername: "Admin Username",
    adminPassword: "Admin Password",
    startLdapService: "Start LDAP Service",
    stopLdapService: "Stop LDAP Service",
    createUser: "Create User",
    createGroup: "Create Group",
  },
  ja: {
    dashboard: "ダッシュボード",
    fileShare: "ファイル共有",
    quickActions: "クイックアクション",
    personalData: "個人データ",
    settings: "設定",
    runningApps: "実行中のアプリ",
    systemStatus: "システム状態",
    recentFiles: "最近のファイル",
    sftpConnection: "SFTP接続",
    smbConnection: "SMB接続",
    serverAddress: "サーバーアドレス",
    username: "ユーザー名",
    password: "パスワード",
    connect: "接続",
    disconnect: "切断",
    connected: "接続済み",
    disconnected: "切断済み",
    addShortcut: "ショートカット追加",
    shortcutName: "ショートカット名",
    command: "コマンド",
    save: "保存",
    delete: "削除",
    edit: "編集",
    notes: "メモ",
    documents: "ドキュメント",
    images: "画像",
    videos: "ビデオ",
    language: "言語",
    theme: "テーマ",
    system: "システム",
    light: "ライト",
    dark: "ダーク",
    cpu: "CPU",
    memory: "メモリ",
    disk: "ディスク",
    network: "ネットワーク",
    addNewItem: "新しいアイテムを追加",
    title: "タイトル",
    type: "タイプ",
    content: "内容",
    add: "追加",
    noNotesStored: "保存されたメモはありません。",
    noDocumentsStored: "保存されたドキュメントはありません。",
    noImagesStored: "保存された画像はありません。",
    noVideosStored: "保存されたビデオはありません。",
    serviceSettings: "サービス設定",
    running: "実行中",
    stopped: "停止中",
    port: "ポート",
    sharedFolder: "共有フォルダ",
    accessPermissions: "アクセス権限",
    readOnly: "読み取り専用",
    readWrite: "読み書き",
    startService: "サービス開始",
    stopService: "サービス停止",
    servicePath: "サービスパス",
    accessLog: "アクセスログ",
    timestamp: "タイムスタンプ",
    user: "ユーザー",
    ipAddress: "IPアドレス",
    action: "アクション",
    file: "ファイル",
    noAccessLogs: "アクセスログがありません。",
    download: "ダウンロード",
    upload: "アップロード",
    view: "表示",
    previous: "前へ",
    next: "次へ",
    page: "ページ",
    of: "の",
    showing: "表示中",
    entries: "件",
    services: "サービス",
    totalServices: "総サービス数",
    activeServices: "アクティブサービス",
    activeConnections: "アクティブ接続",
    dataTransfer: "データ転送",
    serviceStatus: "サービス状態",
    connections: "接続",
    uptime: "稼働時間",
    sftpService: "SFTPサービス",
    smbService: "SMBサービス",
    hours: "時間",
    minutes: "分",
    seconds: "秒",
    shortcutType: "ショートカットタイプ",
    phone: "電話",
    email: "メール",
    website: "ウェブサイト",
    application: "アプリケーション",
    custom: "カスタム",
    phoneNumber: "電話番号",
    emailAddress: "メールアドレス",
    websiteUrl: "ウェブサイトURL",
    applicationPath: "アプリケーションパス",
    customCommand: "カスタムコマンド",
    execute: "実行",
    noShortcutsYet: "まだショートカットが登録されていません。",
    addNewShortcut: "新しいショートカットを追加してください。",
    expandSidebar: "サイドバーを展開",
    collapseSidebar: "サイドバーを折りたたむ",
    addQuickAction: "クイックアクション追加",
    icon: "アイコン",
    selectIcon: "アイコン選択",
    noIcon: "アイコンなし",
    customImage: "カスタム画像",
    uploadCustomIcon: "カスタムアイコンアップロード",
    imageUploaded: "画像アップロード済み",
    ldapServer: "LDAPサーバー",
    ldapConfiguration: "LDAP設定",
    ldapUsers: "LDAPユーザー",
    ldapGroups: "LDAPグループ",
    baseDN: "ベースDN",
    bindDN: "バインドDN",
    bindPassword: "バインドパスワード",
    searchFilter: "検索フィルター",
    userAttributes: "ユーザー属性",
    groupAttributes: "グループ属性",
    connectionTimeout: "接続タイムアウト",
    enableSSL: "SSL有効化",
    enableTLS: "TLS有効化",
    testConnection: "接続テスト",
    connectionSuccessful: "接続成功",
    connectionFailed: "接続失敗",
    syncUsers: "ユーザー同期",
    syncGroups: "グループ同期",
    lastSync: "最終同期",
    ldapHosting: "LDAPホスティング",
    ldapServiceStatus: "LDAPサービス状態",
    hostingPort: "ホスティングポート",
    domainName: "ドメイン名",
    adminUsername: "管理者ユーザー名",
    adminPassword: "管理者パスワード",
    startLdapService: "LDAPサービス開始",
    stopLdapService: "LDAPサービス停止",
    createUser: "ユーザー作成",
    createGroup: "グループ作成",
  },
  zh: {
    dashboard: "仪表板",
    fileShare: "文件共享",
    quickActions: "快速操作",
    personalData: "个人数据",
    settings: "设置",
    runningApps: "运行中的应用",
    systemStatus: "系统状态",
    recentFiles: "最近文件",
    sftpConnection: "SFTP连接",
    smbConnection: "SMB连接",
    serverAddress: "服务器地址",
    username: "用户名",
    password: "密码",
    connect: "连接",
    disconnect: "断开连接",
    connected: "已连接",
    disconnected: "已断开",
    addShortcut: "添加快捷方式",
    shortcutName: "快捷方式名称",
    command: "命令",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    notes: "笔记",
    documents: "文档",
    images: "图片",
    videos: "视频",
    language: "语言",
    theme: "主题",
    system: "系统",
    light: "浅色",
    dark: "深色",
    cpu: "CPU",
    memory: "内存",
    disk: "磁盘",
    network: "网络",
    addNewItem: "添加新项目",
    title: "标题",
    type: "类型",
    content: "内容",
    add: "添加",
    noNotesStored: "没有保存的笔记。",
    noDocumentsStored: "没有保存的文档。",
    noImagesStored: "没有保存的图片。",
    noVideosStored: "没有保存的视频。",
    serviceSettings: "服务设置",
    running: "运行中",
    stopped: "已停止",
    port: "端口",
    sharedFolder: "共享文件夹",
    accessPermissions: "访问权限",
    readOnly: "只读",
    readWrite: "读写",
    startService: "启动服务",
    stopService: "停止服务",
    servicePath: "服务路径",
    accessLog: "访问日志",
    timestamp: "时间戳",
    user: "用户",
    ipAddress: "IP地址",
    action: "操作",
    file: "文件",
    noAccessLogs: "没有访问日志。",
    download: "下载",
    upload: "上传",
    view: "查看",
    previous: "上一页",
    next: "下一页",
    page: "页",
    of: "共",
    showing: "显示",
    entries: "条",
    services: "服务",
    totalServices: "总服务数",
    activeServices: "活跃服务",
    activeConnections: "活跃连接",
    dataTransfer: "数据传输",
    serviceStatus: "服务状态",
    connections: "连接",
    uptime: "运行时间",
    sftpService: "SFTP服务",
    smbService: "SMB服务",
    hours: "小时",
    minutes: "分钟",
    seconds: "秒",
    shortcutType: "快捷方式类型",
    phone: "电话",
    email: "邮件",
    website: "网站",
    application: "应用程序",
    custom: "自定义",
    phoneNumber: "电话号码",
    emailAddress: "邮箱地址",
    websiteUrl: "网站URL",
    applicationPath: "应用程序路径",
    customCommand: "自定义命令",
    execute: "执行",
    noShortcutsYet: "还没有注册的快捷方式。",
    addNewShortcut: "添加新的快捷方式。",
    expandSidebar: "展开侧边栏",
    collapseSidebar: "折叠侧边栏",
    addQuickAction: "添加快速操作",
    icon: "图标",
    selectIcon: "选择图标",
    noIcon: "无图标",
    customImage: "自定义图片",
    uploadCustomIcon: "上传自定义图标",
    imageUploaded: "图片已上传",
    ldapServer: "LDAP服务器",
    ldapConfiguration: "LDAP配置",
    ldapUsers: "LDAP用户",
    ldapGroups: "LDAP组",
    baseDN: "基础DN",
    bindDN: "绑定DN",
    bindPassword: "绑定密码",
    searchFilter: "搜索过滤器",
    userAttributes: "用户属性",
    groupAttributes: "组属性",
    connectionTimeout: "连接超时",
    enableSSL: "启用SSL",
    enableTLS: "启用TLS",
    testConnection: "测试连接",
    connectionSuccessful: "连接成功",
    connectionFailed: "连接失败",
    syncUsers: "同步用户",
    syncGroups: "同步组",
    lastSync: "最后同步",
    ldapHosting: "LDAP托管",
    ldapServiceStatus: "LDAP服务状态",
    hostingPort: "托管端口",
    domainName: "域名",
    adminUsername: "管理员用户名",
    adminPassword: "管理员密码",
    startLdapService: "启动LDAP服务",
    stopLdapService: "停止LDAP服务",
    createUser: "创建用户",
    createGroup: "创建组",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ko")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("caw-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("caw-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[Language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
